[anytls-go]
src.github = "anytls/anytls-go"
fetch.github = "anytls/anytls-go"

[awakened-poe-trade]
src.github = "SnosMe/awakened-poe-trade"
src.prefix = "v"
fetch.url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v$ver/Awakened-PoE-Trade-$ver.AppImage"

[Exiled-Exchange-2]
src.github = "Kvan7/Exiled-Exchange-2"
src.prefix = "v"
fetch.url = "https://github.com/Kvan7/Exiled-Exchange-2/releases/download/v$ver/Exiled-Exchange-2-$ver.AppImage"

[path-of-building]
src.github = "PathOfBuildingCommunity/PathOfBuilding"
fetch.url = "https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/download/$ver/PathOfBuildingCommunity-Portable.zip"

[duckstation]
src.github_tag = "stenzek/duckstation"
src.include_regex = "^v[0-9].*"
fetch.url = "https://github.com/stenzek/duckstation/releases/download/$ver/DuckStation-x64.AppImage"

[proton-cachyos]
src.github = "CachyOS/proton-cachyos"
fetch.url = "https://github.com/CachyOS/proton-cachyos/releases/download/$ver/proton-$ver-x86_64.tar.xz"

[proton-cachyos-x86_64-v3]
src.github = "CachyOS/proton-cachyos"
fetch.url = "https://github.com/CachyOS/proton-cachyos/releases/download/$ver/proton-$ver-x86_64_v3.tar.xz"

[scanocr-server]
src.github_tag = "jigaowan/scanocr"
src.include_regex = "^server/v[0-9]+([.][0-9]+)*$"
src.prefix = "server/v"
fetch.url = "https://github.com/jigaowan/scanocr/releases/download/server%2Fv$ver/scanocr-server-$ver-aarch64-darwin.tar.gz"

[scanocr-client]
src.github_tag = "jigaowan/scanocr"
src.include_regex = "^client/v[0-9]+([.][0-9]+)*$"
fetch.github = "jigaowan/scanocr"

[simslim]
src.github = "MobAI-App/simslim"
fetch.github = "MobAI-App/simslim"
