# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  Exiled-Exchange-2 = {
    pname = "Exiled-Exchange-2";
    version = "0.15.7";
    src = fetchurl {
      url = "https://github.com/Kvan7/Exiled-Exchange-2/releases/download/v0.15.7/Exiled-Exchange-2-0.15.7.AppImage";
      sha256 = "sha256-5wym16j7KjelZxnoJP+KsS0xzTj9PBQf2I3UXkjMhZg=";
    };
  };
  anytls-go = {
    pname = "anytls-go";
    version = "v0.0.12";
    src = fetchFromGitHub {
      owner = "anytls";
      repo = "anytls-go";
      rev = "v0.0.12";
      fetchSubmodules = false;
      sha256 = "sha256-KQNRnDpOb9LxoOWzKgE2r7ipe4qHLrKZcE7rGLTCScY=";
    };
  };
  awakened-poe-trade = {
    pname = "awakened-poe-trade";
    version = "3.28.103";
    src = fetchurl {
      url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.28.103/Awakened-PoE-Trade-3.28.103.AppImage";
      sha256 = "sha256-p/XDWnE9lm/LwT3r/lhQWtEJ3YoaGRFd4Rv7RbdDIeg=";
    };
  };
  duckstation = {
    pname = "duckstation";
    version = "v0.1-11391";
    src = fetchurl {
      url = "https://github.com/stenzek/duckstation/releases/download/v0.1-11391/DuckStation-x64.AppImage";
      sha256 = "sha256-pw7hhKLjcIVhHSTJlpadFOolf+ZY8AXdf+q4lVzCMCY=";
    };
  };
  path-of-building = {
    pname = "path-of-building";
    version = "v2.65.0";
    src = fetchurl {
      url = "https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/download/v2.65.0/PathOfBuildingCommunity-Portable.zip";
      sha256 = "sha256-M52r6iLFVkNr0fgHYkBe0rkQBQDrbpL43nxKz3LPNUg=";
    };
  };
}
