# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  Exiled-Exchange-2 = {
    pname = "Exiled-Exchange-2";
    version = "0.16.3";
    src = fetchurl {
      url = "https://github.com/Kvan7/Exiled-Exchange-2/releases/download/v0.16.3/Exiled-Exchange-2-0.16.3.AppImage";
      sha256 = "sha256-aAHFELdlL7cccpzAW9ROHF1hZDAnQGTLLtDonS0CT2Q=";
    };
  };
  anytls-go = {
    pname = "anytls-go";
    version = "v0.0.13";
    src = fetchFromGitHub {
      owner = "anytls";
      repo = "anytls-go";
      rev = "v0.0.13";
      fetchSubmodules = false;
      sha256 = "sha256-2S/iiLutnvNmxJiphpiRk+14pahXrKrifB9DBJBFQlY=";
    };
  };
  awakened-poe-trade = {
    pname = "awakened-poe-trade";
    version = "3.29.108";
    src = fetchurl {
      url = "https://github.com/SnosMe/awakened-poe-trade/releases/download/v3.29.108/Awakened-PoE-Trade-3.29.108.AppImage";
      sha256 = "sha256-DIksV61mC0E2ZPztWK+WnMqR9KXwLMWQpc7hajaymyE=";
    };
  };
  duckstation = {
    pname = "duckstation";
    version = "v0.1-11894";
    src = fetchurl {
      url = "https://github.com/stenzek/duckstation/releases/download/v0.1-11894/DuckStation-x64.AppImage";
      sha256 = "sha256-wv0mJXrFz+/k93thsEuP4pn5xODPa4UfxSWcgVl5Rmo=";
    };
  };
  magpie = {
    pname = "magpie";
    version = "0.1.1093";
    src = fetchurl {
      url = "https://github.com/yetone/magpie-releases/releases/download/v0.1.1093/magpie-darwin-arm64.dmg";
      sha256 = "sha256-z6rkVUQ13lWGBasap6zAvHO1YeTLHjAodh7rf5X32yc=";
    };
  };
  magpie-aarch64-linux = {
    pname = "magpie-aarch64-linux";
    version = "0.1.1093";
    src = fetchurl {
      url = "https://github.com/yetone/magpie-releases/releases/download/v0.1.1093/magpie-linux-arm64";
      sha256 = "sha256-L6ZLbu06t5taYTJs+pJ8g+URWUH52wDuFuEMpbewWag=";
    };
  };
  magpie-cli-aarch64-darwin = {
    pname = "magpie-cli-aarch64-darwin";
    version = "0.1.1093";
    src = fetchurl {
      url = "https://github.com/yetone/magpie-releases/releases/download/v0.1.1093/magpie-cli-darwin-arm64";
      sha256 = "sha256-WJ7eI04q4PZr03qhi/mWtYvLt6KJyR52AX+b5m1n7t0=";
    };
  };
  magpie-cli-aarch64-linux = {
    pname = "magpie-cli-aarch64-linux";
    version = "0.1.1093";
    src = fetchurl {
      url = "https://github.com/yetone/magpie-releases/releases/download/v0.1.1093/magpie-cli-linux-arm64";
      sha256 = "sha256-2HQJIT6PcFJTDvECjdpJI/oqxTq4DHo0tL0Z8QOj708=";
    };
  };
  magpie-cli-x86_64-darwin = {
    pname = "magpie-cli-x86_64-darwin";
    version = "0.1.1093";
    src = fetchurl {
      url = "https://github.com/yetone/magpie-releases/releases/download/v0.1.1093/magpie-cli-darwin-amd64";
      sha256 = "sha256-oDNoJ0K74fHJXkvMUzO9EtzoWR4o7I0jiNEbxaS2bVY=";
    };
  };
  magpie-cli-x86_64-linux = {
    pname = "magpie-cli-x86_64-linux";
    version = "0.1.1093";
    src = fetchurl {
      url = "https://github.com/yetone/magpie-releases/releases/download/v0.1.1093/magpie-cli-linux-amd64";
      sha256 = "sha256-ziyDGCl5oTocLOxI3Bvfdv/utZ5QHDCttSHu2mkbyF0=";
    };
  };
  magpie-x86_64-linux = {
    pname = "magpie-x86_64-linux";
    version = "0.1.1093";
    src = fetchurl {
      url = "https://github.com/yetone/magpie-releases/releases/download/v0.1.1093/magpie-linux-amd64";
      sha256 = "sha256-uzv1MLS9zLNPXaheQVhpY9+vwQwCEXOXke3a7wy4CvU=";
    };
  };
  path-of-building = {
    pname = "path-of-building";
    version = "v2.67.2";
    src = fetchurl {
      url = "https://github.com/PathOfBuildingCommunity/PathOfBuilding/releases/download/v2.67.2/PathOfBuildingCommunity-Portable.zip";
      sha256 = "sha256-ofMLYMx8khjfKdzT7QmzEbCl/c6MJ9VRf5/h43pGgqc=";
    };
  };
  proton-cachyos = {
    pname = "proton-cachyos";
    version = "cachyos-11.0-20261005-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20261005-slr/proton-cachyos-11.0-20261005-slr-x86_64.tar.xz";
      sha256 = "sha256-CWv+c7UG1lZbBOzEUhQZekCRgY8W7ZH1MktNIILQomM=";
    };
  };
  proton-cachyos-x86_64-v3 = {
    pname = "proton-cachyos-x86_64-v3";
    version = "cachyos-11.0-20261005-slr";
    src = fetchurl {
      url = "https://github.com/CachyOS/proton-cachyos/releases/download/cachyos-11.0-20261005-slr/proton-cachyos-11.0-20261005-slr-x86_64_v3.tar.xz";
      sha256 = "sha256-ulKk8xoGD/yiuOBfwA5RvDnkwVAZKOtakhiw+ge/yMc=";
    };
  };
  scanocr-client = {
    pname = "scanocr-client";
    version = "client/v0.1.1";
    src = fetchFromGitHub {
      owner = "jigaowan";
      repo = "scanocr";
      rev = "client/v0.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-sow6JFoB+sYruVRWxaOtubspB7zA8+LRnBuYuAdEWug=";
    };
  };
  scanocr-server = {
    pname = "scanocr-server";
    version = "0.2.0";
    src = fetchurl {
      url = "https://github.com/jigaowan/scanocr/releases/download/server%2Fv0.2.0/scanocr-server-0.2.0-aarch64-darwin.tar.gz";
      sha256 = "sha256-XirQLOdOZiM7k+HwrNtih1Tj9gaEHqcCMsh8lCh1Vj4=";
    };
  };
  simslim = {
    pname = "simslim";
    version = "v0.11.0";
    src = fetchFromGitHub {
      owner = "MobAI-App";
      repo = "simslim";
      rev = "v0.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-n12sJVXChfegoqdESpztOivjHVUSD9vIFxoqyn3WyrE=";
    };
  };
}
