name: "Auto-update metadata"

on:
  schedule:
    - cron: "36 5 * * *"
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4

      - name: Install nix
        uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Prefetch latest commits of packages
        run: "nix run github:berberman/nvfetcher"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
